yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  react-three-fiber@*:
    dependencies:
      object-assign: "*"
  "@chakra-ui/core@*":
    dependencies:
      "@babel/runtime": "*"
  "toasted-notes@*":
    dependencies:
      "react-spring": "*"
  "@reach/alert@*":
    dependencies:
      "prop-types": "*"
